// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    SocialLink: typeof import('./src/components/SocialLink.vue')['default']
    TheFooter: typeof import('./src/components/layout/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/layout/TheHeader.vue')['default']
    TheLayout: typeof import('./src/components/layout/TheLayout.vue')['default']
    ThePresentation: typeof import('./src/components/ThePresentation.vue')['default']
    TheThemeSwitcher: typeof import('./src/components/layout/TheThemeSwitcher.vue')['default']
  }
}
